In [1]:
import numpy as np
from numpy import linalg as LA

In [2]:
m = 5
n = 3

In [3]:
A = np.empty((m,n))

In [4]:
#Rellenar la matriz manualente
for i in range(0,m):
    for j in range(0,n):
        A[i,j] = 0.23 + 100*i + j

In [5]:
B = 7.52*np.ones((m,n)) #asigna a todos los elementos de la matriz dada el valor dado
C = np.zeros((n,n)) #asigna todos los valores a 0 de la matriz dada
D = np.eye(n,m)

In [6]:
print("A = {}".format(A))
print("B = {}".format(B))
print("C = {}".format(C))
print("D = {}".format(D))

A = [[2.3000e-01 1.2300e+00 2.2300e+00]
 [1.0023e+02 1.0123e+02 1.0223e+02]
 [2.0023e+02 2.0123e+02 2.0223e+02]
 [3.0023e+02 3.0123e+02 3.0223e+02]
 [4.0023e+02 4.0123e+02 4.0223e+02]]
B = [[7.52 7.52 7.52]
 [7.52 7.52 7.52]
 [7.52 7.52 7.52]
 [7.52 7.52 7.52]
 [7.52 7.52 7.52]]
C = [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
D = [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [7]:
#obtener la columna j de la matriz A
print(A[:,2])

[  2.23 102.23 202.23 302.23 402.23]


In [8]:
#obtener la fila i de la matriz A
print(A[1,:])

[100.23 101.23 102.23]


In [9]:
#obtiene la diagonal
print(np.diagonal(A))

[  0.23 101.23 202.23]


In [10]:
#Copia la matriz A en la matriz E
E = np.copy(A)
#print("E = {}".format(E))

In [11]:
#Intercambia la fila i con la fila j
# E[[j,i],:] = E[[i,j],:]
E[[4,0],:] = E[[0,4],:]
print("A' = {}".format(E))

A' = [[4.0023e+02 4.0123e+02 4.0223e+02]
 [1.0023e+02 1.0123e+02 1.0223e+02]
 [2.0023e+02 2.0123e+02 2.0223e+02]
 [3.0023e+02 3.0123e+02 3.0223e+02]
 [2.3000e-01 1.2300e+00 2.2300e+00]]


In [12]:
#Intercambia la columna i con la columna j
# E[:,[j,i]] = E[:,[i,j]]
E = np.copy(A)
E[:,[2,0]] = E[:,[0,2]]
print("A' = {}".format(E))

A' = [[2.2300e+00 1.2300e+00 2.3000e-01]
 [1.0223e+02 1.0123e+02 1.0023e+02]
 [2.0223e+02 2.0123e+02 2.0023e+02]
 [3.0223e+02 3.0123e+02 3.0023e+02]
 [4.0223e+02 4.0123e+02 4.0023e+02]]


In [13]:
#transpuesta
print("A^T = {}".format(A.T))

A^T = [[2.3000e-01 1.0023e+02 2.0023e+02 3.0023e+02 4.0023e+02]
 [1.2300e+00 1.0123e+02 2.0123e+02 3.0123e+02 4.0123e+02]
 [2.2300e+00 1.0223e+02 2.0223e+02 3.0223e+02 4.0223e+02]]


In [14]:
#suma
print("A + B = {}".format(A + B))

A + B = [[  7.75   8.75   9.75]
 [107.75 108.75 109.75]
 [207.75 208.75 209.75]
 [307.75 308.75 309.75]
 [407.75 408.75 409.75]]


In [15]:
#resta
print("A - B = {}".format(A - B))

A - B = [[ -7.29  -6.29  -5.29]
 [ 92.71  93.71  94.71]
 [192.71 193.71 194.71]
 [292.71 293.71 294.71]
 [392.71 393.71 394.71]]


In [16]:
#multiplicación componente por componente
print("A(i,j)*B(i,j) = {}".format(np.multiply(A,B)))

A(i,j)*B(i,j) = [[1.7296000e+00 9.2496000e+00 1.6769600e+01]
 [7.5372960e+02 7.6124960e+02 7.6876960e+02]
 [1.5057296e+03 1.5132496e+03 1.5207696e+03]
 [2.2577296e+03 2.2652496e+03 2.2727696e+03]
 [3.0097296e+03 3.0172496e+03 3.0247696e+03]]


In [17]:
#divide componente por componente
print("A(i,j)/B(i,j) = {}".format(np.divide(A,B)))

A(i,j)/B(i,j) = [[3.05851064e-02 1.63563830e-01 2.96542553e-01]
 [1.33284574e+01 1.34614362e+01 1.35944149e+01]
 [2.66263298e+01 2.67593085e+01 2.68922872e+01]
 [3.99242021e+01 4.00571809e+01 4.01901596e+01]
 [5.32220745e+01 5.33550532e+01 5.34880319e+01]]


In [18]:
#multiplicación por escalar
print("3.9 A = {}".format(3.9*A))

3.9 A = [[8.970000e-01 4.797000e+00 8.697000e+00]
 [3.908970e+02 3.947970e+02 3.986970e+02]
 [7.808970e+02 7.847970e+02 7.886970e+02]
 [1.170897e+03 1.174797e+03 1.178697e+03]
 [1.560897e+03 1.564797e+03 1.568697e+03]]


In [19]:
#suma de un escalar a todos los componentes
print("A + 3.9 = {}".format(A + 3.9))

A + 3.9 = [[  4.13   5.13   6.13]
 [104.13 105.13 106.13]
 [204.13 205.13 206.13]
 [304.13 305.13 306.13]
 [404.13 405.13 406.13]]


In [20]:
#valor maximo
print("max(A) = {}".format(np.max(A)))

max(A) = 402.23


In [21]:
#valor minimo
print("min(A) = {}".format(np.min(A)))

min(A) = 0.23


In [22]:
#1-norma de A
print("||A||_1 = {}".format(LA.norm(A, ord=1)))

||A||_1 = 1011.1500000000001
